"""cascade_deletion

Revision ID: 0ccaadf520b7
Revises: 1fcbecc6aba6
Create Date: 2021-05-10 16:20:20.389795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccaadf520b7'
down_revision = '1fcbecc6aba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
