"""second

Revision ID: 14dbe78b34ac
Revises: eadb198be5a6
Create Date: 2021-05-05 20:04:09.666405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14dbe78b34ac'
down_revision = 'eadb198be5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
