"""recipe_fix

Revision ID: 17d47aff4dc8
Revises: ea8d9cd10783
Create Date: 2021-05-07 20:37:02.085010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d47aff4dc8'
down_revision = 'ea8d9cd10783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
