"""some new

Revision ID: 1f1bafd55d76
Revises: 84e347d62bc5
Create Date: 2021-08-23 18:44:10.256353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1bafd55d76'
down_revision = '84e347d62bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
