"""cascade_deletion

Revision ID: 1fcbecc6aba6
Revises: c993b7078bb4
Create Date: 2021-05-10 11:04:32.299787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcbecc6aba6'
down_revision = 'c993b7078bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
