"""smt

Revision ID: 4798de992a71
Revises: 0ccaadf520b7
Create Date: 2021-05-10 16:24:11.327397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798de992a71'
down_revision = '0ccaadf520b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
