"""Added required tables4

Revision ID: 84e347d62bc5
Revises: 07cbbfe72973
Create Date: 2021-08-23 15:25:02.980668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e347d62bc5'
down_revision = '07cbbfe72973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'new_one')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('new_one', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
