"""boolean_is

Revision ID: 882ce03b9033
Revises: f949874833fa
Create Date: 2021-05-07 11:40:25.360594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882ce03b9033'
down_revision = 'f949874833fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_top_category', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'nutrition', ['id'])
    op.create_unique_constraint(None, 'recipe', ['id'])
    op.create_unique_constraint(None, 'summary', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary', type_='unique')
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_constraint(None, 'nutrition', type_='unique')
    op.drop_column('categories', 'is_top_category')
    # ### end Alembic commands ###
