"""second

Revision ID: bff780aea08c
Revises: 9463fba5bcd8
Create Date: 2021-05-07 00:09:39.839666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff780aea08c'
down_revision = '9463fba5bcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipments',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooker', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.String(length=50), nullable=True),
    sa.Column('preparation_time', sa.String(length=50), nullable=True),
    sa.Column('total_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_table('summaries')
    op.drop_table('images')
    op.drop_table('equipments')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
