"""second

Revision ID: c4abb0a3f42e
Revises: 9d11f4b46fce
Create Date: 2021-05-05 20:30:21.393490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4abb0a3f42e'
down_revision = '9d11f4b46fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
