"""steps v.2

Revision ID: d115acfbcb61
Revises: 33f050e2a226
Create Date: 2021-05-07 20:24:39.438596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd115acfbcb61'
down_revision = '33f050e2a226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'steps', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='unique')
    # ### end Alembic commands ###
