"""associasions_tables

Revision ID: e9c4149e8890
Revises: 17d47aff4dc8
Create Date: 2021-05-07 22:26:17.673496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9c4149e8890'
down_revision = '17d47aff4dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.Column('possible_units', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_a',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('extra_data', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.name'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'equipment_id')
    )
    op.create_table('ingredient_a',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'equipment_id')
    )
    op.create_table('nutrition_a',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('nutrition_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutrition.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'nutrition_id')
    )
    op.drop_table('equipments')
    op.drop_table('ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('possible_units', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ingredients_pkey'),
    sa.UniqueConstraint('id', name='ingredients_id_key'),
    sa.UniqueConstraint('image', name='ingredients_image_key'),
    sa.UniqueConstraint('name', name='ingredients_name_key')
    )
    op.create_table('equipments',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='equipments_pkey'),
    sa.UniqueConstraint('name', name='equipments_name_key')
    )
    op.drop_table('nutrition_a')
    op.drop_table('ingredient_a')
    op.drop_table('equipment_a')
    op.drop_table('ingredient')
    op.drop_table('equipment')
    # ### end Alembic commands ###
