"""steps v.3

Revision ID: ea8d9cd10783
Revises: 21d0345872f6
Create Date: 2021-05-07 20:33:52.857684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea8d9cd10783'
down_revision = '21d0345872f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients', ['id'])
    op.add_column('nutrition', sa.Column('percent_of_daily_needs', sa.Float(), nullable=True))
    op.drop_column('nutrition', 'percentOfDailyNeeds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('percentOfDailyNeeds', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('nutrition', 'percent_of_daily_needs')
    op.drop_constraint(None, 'ingredients', type_='unique')
    # ### end Alembic commands ###
