"""second

Revision ID: eadb198be5a6
Revises: b05bf3dfafe6
Create Date: 2021-05-05 19:01:31.599615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadb198be5a6'
down_revision = 'b05bf3dfafe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
