"""recipes

Revision ID: f949874833fa
Revises: bff780aea08c
Create Date: 2021-05-07 11:24:55.166239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f949874833fa'
down_revision = 'bff780aea08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('influence', sa.Enum('bad', 'neutral', 'good', name='influence'), nullable=True),
    sa.Column('percentOfDailyNeeds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('is_top_recipe', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['cuisine'], ['cuisines.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooker', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.String(length=50), nullable=True),
    sa.Column('preparation_time', sa.String(length=50), nullable=True),
    sa.Column('total_time', sa.String(length=50), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('summaries')
    op.create_unique_constraint(None, 'cuisines', ['name'])
    op.create_unique_constraint(None, 'equipments', ['name'])
    op.add_column('images', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'images', ['id'])
    op.create_foreign_key(None, 'images', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'recipe_id')
    op.drop_constraint(None, 'equipments', type_='unique')
    op.drop_constraint(None, 'cuisines', type_='unique')
    op.create_table('summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cooker', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('servings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cooking_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preparation_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='summaries_pkey')
    )
    op.drop_table('summary')
    op.drop_table('recipe')
    op.drop_table('nutrition')
    # ### end Alembic commands ###
